import { StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 28, fontSize: 8, fontFamily: 'Helvetica', backgroundColor: '#ffffff' },
  header: { marginBottom: 14, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  headerTitle: { fontSize: 13, fontWeight: 'bold', marginBottom: 6 },
  headerRow: { flexDirection: 'row', gap: 20, marginBottom: 2 },
  headerLabel: { color: '#6b7280' },
  headerValue: { fontWeight: 'bold' },
  productSectionHeader: {
    paddingTop: 10,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    marginBottom: 4,
  },
  subGroupBlock: {
    flexDirection: 'row' as const,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 10,
    paddingTop: 6,
    gap: 10,
  },
  subGroupLabel: {
    fontSize: 9,
    fontWeight: 'bold' as const,
    marginBottom: 4,
    color: '#374151',
  },
  imageBox: { width: 64, height: 64, flexShrink: 0 },
  productImage: { width: 64, height: 64, objectFit: 'cover', borderRadius: 2 },
  imagePlaceholder: { width: 64, height: 64, backgroundColor: '#f3f4f6', borderRadius: 2 },
  productContent: { flex: 1 },
  productName: { fontSize: 9, fontWeight: 'bold', marginBottom: 2 },
  productLink: { fontSize: 7, color: '#2563eb', marginBottom: 6, textDecoration: 'none' },
  table: { marginTop: 4 },
  tableRow: { flexDirection: 'row', paddingVertical: 2 },
  tableHeaderRow: { flexDirection: 'row', paddingVertical: 3, borderBottomWidth: 1, borderBottomColor: '#d1d5db', backgroundColor: '#f9fafb' },
  subtotalRow: { borderTopWidth: 1, borderTopColor: '#d1d5db', paddingTop: 4, marginTop: 2 },
  colVariant: { flex: 3, paddingHorizontal: 2 },
  colQty: { width: 32, textAlign: 'right', paddingHorizontal: 2 },
  colPrice: { width: 48, textAlign: 'right', paddingHorizontal: 2 },
  colTotal: { width: 56, textAlign: 'right', paddingHorizontal: 2, fontWeight: 'bold' },
  headerText: { color: '#6b7280', fontSize: 7 },
  subtotalText: { fontWeight: 'bold', fontSize: 8 },
  footer: {
    marginTop: 16,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 24,
  },
  footerLabel: { color: '#6b7280' },
  footerValue: { fontWeight: 'bold', fontSize: 9 },
})

export default styles
